### PR TITLE
move to grunt-dojo2 for build pipeline

### LINKED ISSUE #37: master build is failing
[Most recent failing build](https://travis-ci.org/dojo/typings/builds/157369581)

### PR DESCRIPTION
**Pull request by agubler**
resolves #37

### CODE REVIEW

File: Gruntfile.js [hunk 1]
```diff
@@ -1,61 +1,11 @@
...
+	require('grunt-dojo2').initConfig(grunt, {
+		dtsGenerator: {
 			options: {
-				configuration: grunt.file.readJSON('tslint.json')
-			},
-			src: {
-				src: [
-					'<%= all %>'
-				]
+				main: 'dojo-core/main'
```
Comment (kitsonk) [inline Gruntfile.js]: Hmmm??  Don't we just drop this one for this package?

Comment (agubler) [reply Gruntfile.js]: ah that's a mistake on my part.
